name: Check

on: [push, pull_request]
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
      CI: true
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      DSL_SPREADSHEET_BUILDER_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_SECRET }}
      LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Decrypt Stored Credentials
        run: ./libs/spreadsheet-builder-google/tokens/decrypt_secret.sh
      - uses: gradle/gradle-command-action@v2
        with:
          arguments: check coveralls --stacktrace
